spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.mate
  default-consumes-media-type: application/json
  default-produces-media-type: application/json