### [Match API] ###
####################

### 전체 경기 조회 ###
### 메인 배너용 경기 조회(5개) (상단 배너)
GET http://localhost:8080/api/matches/main
Content-Type: application/json

### 팀별 경기 조회 (3개) (상단 배너)
GET http://localhost:8080/api/matches/team/1
Content-Type: application/json

### 팀별 완료된 경기 전적 조회
### KIA 팀 완료된 경기 전적 조회
GET http://localhost:8080/api/matches/team/1/completed
Content-Type: application/json

### 팀별 주차별 경기 일정 조회 (KIA) - 날짜 지정
GET http://localhost:8080/api/matches/team/1/weekly?startDate=2024-11-15
Content-Type: application/json

### 팀별 주차별 경기 일정 조회 (KIA) - 오늘 날짜 기준
GET http://localhost:8080/api/matches/team/2/weekly
Content-Type: application/json
Authorization: Bearer

### [Team API] ###
#################

### KBO 리그 전체 순위를 조회
GET http://localhost:8000/api/teams/rankings
Content-Type: application/json

### 특정 팀 순위 조회
GET http://localhost:8000/api/teams/rankings/6
Content-Type: application/json