### [Match API] ###
####################

### 1. 전체 경기 조회 ###
### 메인 배너용 경기 조회 (5개) (상단 배너)
GET http://localhost:8000/api/matches/main
Content-Type: application/json

### 팀별 경기 조회 (3개) (상단 배너)
GET http://localhost:8000/api/matches/team/1
Content-Type: application/json

### 팀별 완료된 경기 전적 조회
### KIA 팀 완료된 경기 전적 조회
GET http://localhost:8000/api/matches/team/1/completed
Content-Type: application/json

### [Team API] ###
#################